try{
    let a = 0;
    console.log(program)
    console.log("Program run successfully...")
}
catch(error){
    console.log("This is a error..")
    console.log(p)      // error in catch
}

/*finally{
    console.log("Finally execute always...")
}
*/ 